# Sample usage for auto-translate documentation by using Claude Code Action
# The following approach is a reusable workflow that calls the centralized workflow file (.github/workflows/auto-translate-docs-reusable.yml) in the josh-wong/actions from any repository.
# NOTE: Name this file ".github/workflows/auto-translate-docs-reusable.yml"

name: Auto-translate documentation (ja-jp)
on:
  pull_request:
    types: [closed]
    paths:
      - "docs/en-us/**/*.mdx"
      - "docs/en-us/**/*.md"
  workflow_dispatch:
    inputs:
      pr_number:
        description: 'PR number to translate (optional)'
        required: false
        type: string

jobs:
  translate-docs:
    uses: josh-wong/actions/.github/workflows/auto-translate-documentation-reusable.yml@main
    with:
      pr_number: ${{ inputs.pr_number || '' }}
    secrets:
      CLAUDE_CODE_OAUTH_TOKEN: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
