name: Auto Translate Markdown (Official Claude Code Action)
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "docs/en-us/**/*.mdx"
      - "docs/en-us/**/*.md"

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write  # Required for OIDC authentication with Claude

jobs:
  auto-translate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-translate documentation with Claude
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          direct_prompt: |
            I need you to automatically translate English documentation files to Japanese and create organized translations.

            ## Task Overview:
            Detect any modified English documentation files in the `docs/en-us/` directory and create Japanese translations in the `docs/ja-jp/` directory with the same structure.

            ## Instructions:
            1. **Find Modified Files**: Use glob and grep tools to identify modified .mdx and .md files in `docs/en-us/`
            2. **Translation Requirements**:
               - Translate all text content from English to Japanese
               - Preserve all MDX/Markdown formatting, syntax, and structure
               - Keep code blocks, URLs, and technical terms in English where appropriate
               - Maintain the same file structure in `docs/ja-jp/` as exists in `docs/en-us/`
            3. **File Management**:
               - Create the `docs/ja-jp/` directory structure if it doesn't exist
               - Name translated files with the same names as the source files
               - Ensure proper UTF-8 encoding for Japanese text
            4. **Quality Standards**:
               - Use natural, professional Japanese
               - Maintain technical accuracy
               - Preserve all links, code examples, and formatting

            ## Expected Output:
            - Japanese translations of all modified English documentation files
            - Proper directory structure mirroring the English docs
            - A summary comment of what files were translated

            Please analyze the changed files in this PR and create the appropriate Japanese translations.

          # Enable necessary tools for file operations and git
          # View: Read files, Edit: Modify files, Glob: Find files, Grep: Search content
          # Bash with git operations for committing changes
          allowed_tools: "View,Edit,Glob,Grep,Bash(git:*),Bash(mkdir:*),Bash(find:*)"
          
          # Set timeout for translation work
          timeout_minutes: 15
