name: Auto-Translate Documentation
on:
  pull_request:
    types: [closed]
    paths:
      - "docs/en-us/**/*.mdx"
      - "docs/en-us/**/*.md"

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  auto-translate:
    runs-on: ubuntu-latest
    # Only run if PR was merged (not just closed)
    if: github.event.pull_request.merged == true
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Auto-translate documentation to Japanese
        uses: anthropics/claude-code-action@beta
        with:
          claude_code_oauth_token: ${{ secrets.CLAUDE_CODE_OAUTH_TOKEN }}
          # anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}  # Alternative auth method - uncomment if using API key instead
          direct_prompt: |
            A documentation PR has just been merged. Please translate any English documentation changes to Japanese.

            ## Task:
            1. Identify files that were changed in the merged PR in the docs/en-us/ directory
            2. For each changed file, create or update the corresponding Japanese translation in docs/ja-jp/
            3. Maintain the same directory structure and filename in the Japanese docs

            ## Requirements:
            - Translate all English text to natural, professional Japanese
            - Preserve all MDX/Markdown formatting exactly (headers, lists, code blocks, links)
            - Keep code examples, URLs, and technical terms in English
            - Ensure proper UTF-8 encoding for Japanese characters
            - Create docs/ja-jp/ directory structure if it doesn't exist

            ## Process:
            1. Use git to identify which files were modified in the merged PR
            2. Read each modified English documentation file
            3. Create high-quality Japanese translations
            4. Save translations in docs/ja-jp/ with identical file structure
            5. Commit the translations with a descriptive message

            Please analyze the merged PR and create the necessary Japanese translations.

          allowed_tools: "View,Edit,Glob,Grep,Bash(git:*),Bash(mkdir:*)"
          timeout_minutes: 20
