# .github/workflows/auto-translate-markdown.yml
name: Auto-Translate Markdown to Japanese

on:
  pull_request:
    types: [closed]
    paths:
      - 'docs/en-us/**/*.md'
      - 'docs/en-us/**/*.mdx'
  workflow_dispatch:  # Allows manual triggering for testing

jobs:
  translate-markdown:
    if: github.event.pull_request.merged == true
    uses: josh-wong/actions/.github/workflows/auto-translate-markdown-claude-reusable.yml@main
    env:
      ANTHROPIC_API_KEY: ${{ secrets.ANTHROPIC_API_KEY }}
      # GITHUB_TOKEN is automatically available and doesn't need to be passed
