name: Auto-translate Markdown docs from English to Japanese

on:
  workflow_call:
    inputs:
      output_dir:
        required: false
        type: string
        default: 'docs/ja-jp'
        description: 'Directory where the generated translation will be saved'
      file_extension:
        required: false
        type: string
        default: 'mdx'
        description: 'File extension for the generated documentation file (e.g., md, mdx)'
    secrets:
      OPENAI_API_KEY_ACTION_TRANSLATE_DOCS:
        required: true
        description: 'API key for OpenAI'

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install openai

      - name: Get changed files
        id: changes
        run: |
          echo "files=$(git diff --name-only ${{ github.event.before }} ${{ github.sha }} -- 'docs/en-us/' | tr '\n' ' ')" >> $GITHUB_OUTPUT

      - name: Translate updated files
        if: steps.changes.outputs.files != ''
        env:
          OPENAI_API_KEY_ACTION_TRANSLATE_DOCS: ${{ secrets.OPENAI_API_KEY_ACTION_TRANSLATE_DOCS }}
          OUTPUT_DIR: ${{ inputs.output_dir }}
          FILE_EXTENSION: ${{ inputs.file_extension }}
        run: |
          mkdir -p ${{ inputs.output_dir }}
          for file in ${{ steps.changes.outputs.files }}; do
            echo "Translating $file"
            python auto-translate-markdown-script/auto-translate.py "$file" "${{ inputs.output_dir }}" "${{ inputs.file_extension }}"
          done

      - name: Debug - List translated files
        run: |
          echo "Contents of ${{ inputs.output_dir }}:"
          ls -la ${{ inputs.output_dir }}

      - name: Get English PR title
        id: get_pr_title
        if: github.event_name == 'pull_request'
        run: |
          PR_TITLE=$(gh pr view ${{ github.event.pull_request.number }} --json title -q '.title')
          echo "title=${PR_TITLE}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR with translated docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH="translate-ja-${{ github.run_id }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b $BRANCH
          git add ${{ inputs.output_dir }}
          # Only commit and create PR if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "Translate doc to Japanese"
            git push origin $BRANCH

            if [ "${{ github.event_name }}" == "pull_request" ]; then
              PR_TITLE="[Japanese] ${{ steps.get_pr_title.outputs.title }}"
            else
              PR_TITLE="[Japanese] Translation update"
            fi

            gh pr create --title "$PR_TITLE" \
                        --body "Automated translation of new English doc" \
                        --base ${{ github.ref_name }} \
                        --head $BRANCH
          fi
