name: Auto Translate Documentation
on:
  pull_request:
    types: [opened, synchronize]
    paths:
      - "docs/en-us/**/*.mdx"
      - "docs/en-us/**/*.md"

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  translate-docs:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Translate documentation automatically
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          mode: agent
          direct_prompt: |
            Task: Automatically translate modified English documentation to Japanese

            Analysis required:
            1. Find all modified .mdx and .md files in docs/en-us/ directory from this PR
            2. For each modified file, create a Japanese translation in docs/ja-jp/ with same directory structure
            
            Translation requirements:
            - Translate all English text to natural Japanese
            - Preserve MDX/Markdown formatting exactly
            - Keep code blocks, URLs, and technical terms unchanged
            - Maintain all file structure and naming
            
            Steps:
            1. Use Glob to find all files in docs/en-us/
            2. Use git diff to identify which files were modified in this PR
            3. Read each modified file with View tool
            4. Create Japanese translation maintaining exact formatting
            5. Use Edit tool to create translated files in docs/ja-jp/ directory
            6. Commit the translated files with appropriate message
            
            Create comprehensive Japanese translations for all modified documentation files.

          allowed_tools: "View,Edit,Glob,Grep,Bash(git:*),Bash(mkdir:*)"
          timeout_minutes: 20
