name: Auto-translate Markdown docs from English to Japanese

on:
  workflow_call:
    inputs:
      output_dir:
        required: false
        type: string
        default: 'docs/ja-jp'
        description: 'Directory where the generated translation will be saved'
      file_extension:
        required: false
        type: string
        default: 'mdx'
        description: 'File extension for the generated documentation file (e.g., md, mdx)'
      source_dir:
        required: false
        type: string
        default: 'docs/en-us'
        description: 'Source directory containing English documents'
      specific_files:
        required: false
        type: string
        default: ''
        description: 'Comma-separated list of specific files to translate (relative to repo root)'
      translate_all:
        required: false
        type: boolean
        default: false
        description: 'Whether to translate all files in the source directory'
    secrets:
      OPENAI_API_KEY_ACTION_TRANSLATE_DOCS:
        required: true
        description: 'API key for OpenAI'

jobs:
  translate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Create translation script
        run: |
          cat > translate_script.py << 'EOL'
          import os
          import sys
          import openai
          from pathlib import Path

          openai.api_key = os.getenv("OPENAI_API_KEY_ACTION_TRANSLATE_DOCS")

          def translate_file(source_path, output_dir, file_extension=None):
              with open(source_path, "r", encoding="utf-8") as f:
                  content = f.read()

              prompt = f"Translate the following Markdown documentation from English to Japanese:\n\n{content}"

              try:
                  response = openai.ChatCompletion.create(
                      model="gpt-4o",
                      messages=[{"role": "user", "content": prompt}],
                      temperature=0.3,
                  )
                  translation = response['choices'][0]['message']['content']

                  # Get the relative path from source_path
                  source_rel_path = Path(source_path).name

                  # Determine target file extension
                  if file_extension:
                      target_ext = file_extension
                  else:
                      target_ext = Path(source_path).suffix.lstrip('.')

                  # Create target path in the specified output directory
                  target_path = Path(output_dir) / f"{Path(source_path).stem}.{target_ext}"

                  print(f"Saving translation to {target_path}")
                  os.makedirs(os.path.dirname(target_path), exist_ok=True)
                  with open(target_path, "w", encoding="utf-8") as f:
                      f.write(translation)
                  print(f"Successfully translated {source_path} to {target_path}")

              except Exception as e:
                  print(f"Error translating {source_path}: {str(e)}")
                  raise e

          if __name__ == "__main__":
              if len(sys.argv) < 2:
                  print("Usage: python translate_script.py <source_file> [output_dir] [file_extension]")
                  sys.exit(1)

              source = Path(sys.argv[1])

              output_dir = "docs/ja-jp"  # Default output directory
              if len(sys.argv) > 2:
                  output_dir = sys.argv[2]

              file_extension = None
              if len(sys.argv) > 3:
                  file_extension = sys.argv[3]

              translate_file(source, output_dir, file_extension)
          EOL
          chmod +x translate_script.py

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.x'

      - name: Install dependencies
        run: pip install openai

      - name: Get files to translate based on inputs
        id: get_files
        run: |
          # Priority 1: Specific files specified in inputs
          if [[ -n "${{ inputs.specific_files }}" ]]; then
            echo "Using specifically listed files"
            echo "files=${{ inputs.specific_files }}" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Priority 2: All files in source directory if translate_all is true
          if [[ "${{ inputs.translate_all }}" == "true" ]]; then
            echo "Translating all files in ${{ inputs.source_dir }}"
            FILES=$(find ${{ inputs.source_dir }} -type f -name "*.md*" | tr '\n' ' ')
            echo "files=${FILES}" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Priority 3: Changed files in pull request
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "Getting changed files from pull request"
            CHANGED=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }} -- '${{ inputs.source_dir }}/' | tr '\n' ' ')
            echo "files=${CHANGED}" >> $GITHUB_OUTPUT
            exit 0
          fi

          # Priority 4: Recently changed files on the branch (last commit)
          echo "Getting changed files from last commit"
          if [[ -n "${{ github.event.before }}" ]]; then
            COMP_SHA="${{ github.event.before }}"
          else
            # Use HEAD^ if not workflow_dispatch
            COMP_SHA="HEAD^"
          fi
          CHANGED=$(git diff --name-only ${COMP_SHA} HEAD -- '${{ inputs.source_dir }}/' | tr '\n' ' ')
          echo "files=${CHANGED}" >> $GITHUB_OUTPUT

      - name: List files to translate
        run: |
          echo "Files to translate:"
          for file in ${{ steps.get_files.outputs.files }}; do
            echo "- $file"
          done
          
          # Debug information about repository structure
          echo "Current working directory: $(pwd)"
          echo "Repository contents:"
          ls -la

      - name: Translate files
        if: steps.get_files.outputs.files != ''
        env:
          OPENAI_API_KEY_ACTION_TRANSLATE_DOCS: ${{ secrets.OPENAI_API_KEY_ACTION_TRANSLATE_DOCS }}
          OUTPUT_DIR: ${{ inputs.output_dir }}
          FILE_EXTENSION: ${{ inputs.file_extension }}
        run: |
          mkdir -p ${{ inputs.output_dir }}
          for file in ${{ steps.get_files.outputs.files }}; do
            echo "Translating $file"
            python translate_script.py "$file" "${{ inputs.output_dir }}" "${{ inputs.file_extension }}"
          done

      - name: Debug - List translated files
        run: |
          echo "Contents of ${{ inputs.output_dir }}:"
          if [ -d "${{ inputs.output_dir }}" ]; then
            find "${{ inputs.output_dir }}" -type f -name "*.${{ inputs.file_extension }}" | sort
          else
            echo "Output directory does not exist"
          fi

      - name: Get English PR title
        id: get_pr_title
        if: github.event_name == 'pull_request'
        run: |
          PR_TITLE=$(gh pr view ${{ github.event.pull_request.number }} --json title -q '.title')
          echo "title=${PR_TITLE}" >> $GITHUB_OUTPUT
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Create PR with translated docs
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          BRANCH="translate-ja-${{ github.run_id }}"
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git checkout -b $BRANCH
          git add ${{ inputs.output_dir }}
          # Only commit and create PR if there are changes
          if git diff --staged --quiet; then
            echo "No changes to commit"
            exit 0
          else
            git commit -m "Translate doc to Japanese"
            git push origin $BRANCH

            if [ "${{ github.event_name }}" == "pull_request" ]; then
              PR_TITLE="[Japanese] ${{ steps.get_pr_title.outputs.title }}"
            else
              PR_TITLE="[Japanese] Translation update"
            fi

            gh pr create --title "$PR_TITLE" \
                        --body "Automated translation of new English doc" \
                        --base ${{ github.ref_name }} \
                        --head $BRANCH
          fi
