name: Test Claude Translation
on:
  workflow_dispatch:
    inputs:
      test_message:
        description: 'Test message for Claude'
        required: false
        default: 'Translate documentation'

permissions:
  contents: write
  pull-requests: write
  issues: write
  id-token: write

jobs:
  test-claude:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Test Claude Code Action
        uses: anthropics/claude-code-action@beta
        with:
          anthropic_api_key: ${{ secrets.ANTHROPIC_API_KEY }}
          direct_prompt: |
            Test prompt: ${{ github.event.inputs.test_message }}
            
            Please verify that you can:
            1. Read files from the repository
            2. Access the file system
            3. View the current directory structure
            
            If this is working correctly, please create a test file at `/tmp/claude-test-success.txt` with the content "Claude Code Action is working properly!"
            
            Then list the contents of the docs directory if it exists.

          allowed_tools: "View,Edit,Glob,Grep,Bash"
          timeout_minutes: 5
